version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: localsvn-postgres
    environment:
      POSTGRES_DB: localsvn
      POSTGRES_USER: localsvn_user
      POSTGRES_PASSWORD: localsvn_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localsvn_user -d localsvn"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: localsvn-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@locals.vn
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
